import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { StationLogo } from "@/components/station-logo";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useRadioPlayer, type Radio } from "@/lib/radio-player";

const FILTERS = ["Todas", "Pop latino", "Noticias", "Música", "Actualidad"];
function RadioListItem({ radio }: { radio: Radio }) {
  const { playRadio, toggleFavorite, isFavorite, currentRadio } = useRadioPlayer();
  return <Pressable onPress={() => playRadio(radio)} style={({ pressed }) => [styles.item, pressed && { opacity: 0.75 }]}><StationLogo radio={radio} size={54} radius={16} /><View style={{ flex: 1 }}><Text style={styles.name}>{radio.name}</Text><Text style={styles.meta}>{radio.frequency}  ·  {radio.city}</Text></View><Pressable onPress={() => toggleFavorite(radio.id)} hitSlop={10}><IconSymbol name={isFavorite(radio.id) ? "heart.fill" : "heart"} size={19} color={isFavorite(radio.id) ? "#FF6B5F" : "#8D95A7"} /></Pressable><View style={styles.play}><IconSymbol name={currentRadio?.id === radio.id ? "pause.fill" : "play.fill"} size={14} color="#F5F3EE" /></View></Pressable>;
}
export default function ExploreScreen() {
  const { radios } = useRadioPlayer();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("Todas");
  const data = useMemo(() => radios.filter((r) => (filter === "Todas" || r.genre === filter) && `${r.name} ${r.city} ${r.genre}`.toLowerCase().includes(query.toLowerCase())), [query, filter, radios]);
  return <ScreenContainer containerClassName="bg-[#090B12]" className="px-5 pt-3"><FlatList data={data} keyExtractor={(r) => r.id} showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 30 }} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.eyebrow}>DIRECTORIO</Text><Text style={styles.title}>Explora Chile</Text></View><View style={styles.count}><Text style={styles.countText}>{data.length}</Text></View></View><View style={styles.search}><IconSymbol name="magnifyingglass" size={18} color="#A8B0C2" /><TextInput value={query} onChangeText={setQuery} placeholder="Buscar emisora" placeholderTextColor="#7F8799" style={styles.input} /></View><FlatList data={FILTERS} horizontal showsHorizontalScrollIndicator={false} keyExtractor={(x) => x} contentContainerStyle={{ gap: 8, paddingBottom: 25 }} renderItem={({ item }) => <Pressable onPress={() => setFilter(item)} style={[styles.chip, filter === item && styles.chipActive]}><Text style={[styles.chipText, filter === item && styles.chipTextActive]}>{item}</Text></Pressable>} /></>} renderItem={({ item }) => <RadioListItem radio={item} />} ListEmptyComponent={<Text style={styles.empty}>No hay radios para este filtro.</Text>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 22 }, eyebrow: { color: "#FF8C7F", fontSize: 11, fontWeight: "700", letterSpacing: 1.8, marginBottom: 7 }, title: { color: "#F5F3EE", fontSize: 32, fontWeight: "700", letterSpacing: -1 }, count: { width: 38, height: 38, borderRadius: 14, backgroundColor: "#FFFFFF0D", alignItems: "center", justifyContent: "center" }, countText: { color: "#FF8C7F", fontWeight: "700" }, search: { height: 48, borderRadius: 16, backgroundColor: "#FFFFFF0D", borderWidth: 1, borderColor: "#FFFFFF14", flexDirection: "row", alignItems: "center", paddingHorizontal: 15, marginBottom: 17 }, input: { flex: 1, color: "#F5F3EE", marginLeft: 10, fontSize: 14 }, chip: { borderRadius: 99, paddingHorizontal: 15, height: 34, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF0A", borderWidth: 1, borderColor: "#FFFFFF10" }, chipActive: { backgroundColor: "#FF6B5F", borderColor: "#FF6B5F" }, chipText: { color: "#9AA2B3", fontSize: 12, fontWeight: "600" }, chipTextActive: { color: "#090B12" }, item: { minHeight: 75, borderRadius: 19, backgroundColor: "#FFFFFF08", borderWidth: 1, borderColor: "#FFFFFF0E", padding: 10, marginBottom: 10, flexDirection: "row", alignItems: "center", gap: 13 }, name: { color: "#F5F3EE", fontSize: 15, fontWeight: "600" }, meta: { color: "#8D95A7", fontSize: 12, marginTop: 5 }, play: { width: 30, height: 30, borderRadius: 15, backgroundColor: "#FFFFFF14", alignItems: "center", justifyContent: "center" }, empty: { color: "#A8B0C2", textAlign: "center", paddingTop: 30 } });
