import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "expo-router";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { StationLogo } from "@/components/station-logo";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useRadioPlayer, type Radio } from "@/lib/radio-player";
import { useThemeContext } from "@/lib/theme-provider";
import { favoriteAddedHaptic, favoriteRemovedHaptic } from "@/lib/haptics";
import { FavoriteToast } from "@/components/favorite-toast";
import { AnimatedFavoriteIcon } from "@/components/animated-favorite-icon";

const FILTERS = ["Todas", "Pop latino", "Noticias", "Música", "Actualidad"];
function RadioListItem({ radio, onFavorite }: { radio: Radio; onFavorite: (id: string, name: string) => void }) {
  const router = useRouter();
  const { playRadio, isFavorite, currentRadio, isLoading, isPlaying } = useRadioPlayer();
  const { colorScheme } = useThemeContext();
  const lightMode = colorScheme === "light";
  return <Pressable onPress={() => router.push(`/radio/${radio.id}`)} style={({ pressed }) => [styles.item, lightMode && styles.itemLight, pressed && { opacity: 0.75 }]}><StationLogo radio={radio} size={54} radius={16} /><View style={{ flex: 1 }}><Text style={[styles.name, lightMode && styles.nameLight]}>{radio.name}</Text><Text style={[styles.meta, lightMode && styles.metaLight]}>{radio.frequency}  ·  {radio.city}</Text></View><Pressable onPress={() => onFavorite(radio.id, radio.name)} hitSlop={10} accessibilityRole="button" accessibilityLabel={isFavorite(radio.id) ? `Quitar ${radio.name} de favoritos` : `Guardar ${radio.name} en favoritos`} accessibilityState={{ selected: isFavorite(radio.id) }} style={({ pressed }) => [styles.favoriteButton, isFavorite(radio.id) && styles.favoriteButtonActive, pressed && styles.controlPressed]}><AnimatedFavoriteIcon active={isFavorite(radio.id)} color={isFavorite(radio.id) ? "#D64E4A" : lightMode ? "#667085" : "#8D95A7"} /></Pressable><Pressable onPress={() => playRadio(radio)} accessibilityRole="button" accessibilityLabel={isLoading && currentRadio?.id === radio.id ? `Conectando con ${radio.name}` : isPlaying && currentRadio?.id === radio.id ? `Pausar ${radio.name}` : `Reproducir ${radio.name}`} style={({ pressed }) => [styles.play, lightMode && styles.playLight, isPlaying && currentRadio?.id === radio.id && styles.playActive, pressed && styles.controlPressed]}>{isLoading && currentRadio?.id === radio.id ? <ActivityIndicator size="small" color={lightMode ? "#F8FAFC" : "#F5F3EE"} /> : <IconSymbol name={isPlaying && currentRadio?.id === radio.id ? "pause.fill" : "play.fill"} size={14} color={lightMode ? "#F8FAFC" : "#F5F3EE"} />}</Pressable></Pressable>;
}
export default function ExploreScreen() {
  const { radios, isFavorite, toggleFavorite } = useRadioPlayer();
  const [favoriteNotice, setFavoriteNotice] = useState<string | null>(null);
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { if (toastTimer.current) clearTimeout(toastTimer.current); }, []);
  const handleFavorite = (id: string, name: string) => { const saved = !isFavorite(id); toggleFavorite(id); if (saved) favoriteAddedHaptic(); else favoriteRemovedHaptic(); setFavoriteNotice(saved ? `${name} guardada en favoritos` : `${name} quitada de favoritos`); if (toastTimer.current) clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setFavoriteNotice(null), 1700); };
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("Todas");
  const data = useMemo(() => radios.filter((r) => (filter === "Todas" || r.genre === filter) && `${r.name} ${r.city} ${r.genre}`.toLowerCase().includes(query.toLowerCase())), [query, filter, radios]);
  return <ScreenContainer containerClassName="bg-[#090B12]" className="px-5 pt-3"><FlatList data={data} keyExtractor={(r) => r.id} showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 30 }} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.eyebrow}>DIRECTORIO</Text><Text style={styles.title}>Explora Chile</Text></View><View style={styles.count}><Text style={styles.countText}>{data.length}</Text></View></View><View style={styles.search}><IconSymbol name="magnifyingglass" size={18} color="#A8B0C2" /><TextInput value={query} onChangeText={setQuery} placeholder="Buscar emisora" placeholderTextColor="#7F8799" style={styles.input} /></View><FlatList data={FILTERS} horizontal showsHorizontalScrollIndicator={false} keyExtractor={(x) => x} contentContainerStyle={{ gap: 8, paddingBottom: 25 }} renderItem={({ item }) => <Pressable onPress={() => setFilter(item)} style={[styles.chip, filter === item && styles.chipActive]}><Text style={[styles.chipText, filter === item && styles.chipTextActive]}>{item}</Text></Pressable>} /></>} renderItem={({ item }) => <RadioListItem radio={item} onFavorite={handleFavorite} />} ListEmptyComponent={<Text style={styles.empty}>No hay radios para este filtro.</Text>} /><FavoriteToast message={favoriteNotice} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 22 }, eyebrow: { color: "#FF8C7F", fontSize: 11, fontWeight: "700", letterSpacing: 1.8, marginBottom: 7 }, title: { color: "#F5F3EE", fontSize: 32, fontWeight: "700", letterSpacing: -1 }, count: { width: 38, height: 38, borderRadius: 14, backgroundColor: "#FFFFFF0D", alignItems: "center", justifyContent: "center" }, countText: { color: "#FF8C7F", fontWeight: "700" }, search: { height: 48, borderRadius: 16, backgroundColor: "#FFFFFF0D", borderWidth: 1, borderColor: "#FFFFFF14", flexDirection: "row", alignItems: "center", paddingHorizontal: 15, marginBottom: 17 }, input: { flex: 1, color: "#F5F3EE", marginLeft: 10, fontSize: 14 }, chip: { borderRadius: 99, paddingHorizontal: 15, height: 34, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF0A", borderWidth: 1, borderColor: "#FFFFFF10" }, chipActive: { backgroundColor: "#D64E4A", borderColor: "#D64E4A" }, chipText: { color: "#9AA2B3", fontSize: 12, fontWeight: "600" }, chipTextActive: { color: "#FFFFFF" }, itemLight: { backgroundColor: "#FFFFFFD9", borderColor: "#D9E0EC" }, nameLight: { color: "#172033" }, metaLight: { color: "#5B667B" }, playLight: { backgroundColor: "#172033" }, playActive: { backgroundColor: "#D64E4A" }, favoriteButton: { padding: 8, borderRadius: 12 }, favoriteButtonActive: { backgroundColor: "#FF6B5F1C" }, controlPressed: { opacity: 0.62, transform: [{ scale: 0.94 }] },
item: { minHeight: 75, borderRadius: 19, backgroundColor: "#FFFFFF08", borderWidth: 1, borderColor: "#FFFFFF0E", padding: 10, marginBottom: 10, flexDirection: "row", alignItems: "center", gap: 13 }, name: { color: "#F5F3EE", fontSize: 15, fontWeight: "600" }, meta: { color: "#8D95A7", fontSize: 12, marginTop: 5 }, play: { width: 30, height: 30, borderRadius: 15, backgroundColor: "#FFFFFF14", alignItems: "center", justifyContent: "center" }, empty: { color: "#A8B0C2", textAlign: "center", paddingTop: 30 } });
