import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Switch, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useState } from "react";

export default function SettingsScreen() {
  const router = useRouter(); const [background, setBackground] = useState(true); const [haptics, setHaptics] = useState(true);
  return <ScreenContainer containerClassName="bg-[#090B12]" className="px-5 pt-3"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.left" size={22} color="#F5F3EE" /></Pressable><Text style={styles.title}>Ajustes</Text><View style={{ width: 38 }} /></View><Text style={styles.eyebrow}>REPRODUCCIÓN</Text><View style={styles.group}><SettingRow icon="moon.fill" title="Seguir reproduciendo" subtitle="Mantén la radio activa al salir" value={background} onChange={setBackground} /><View style={styles.divider} /><SettingRow icon="waveform" title="Respuesta háptica" subtitle="Un toque sutil al interactuar" value={haptics} onChange={setHaptics} /></View><Text style={styles.eyebrow}>ACERCA DE</Text><View style={styles.group}><View style={styles.about}><View style={styles.aboutIcon}><IconSymbol name="radio" size={23} color="#FF8C7F" /></View><View style={{ flex: 1 }}><Text style={styles.aboutTitle}>Radio Chile Glass</Text><Text style={styles.aboutText}>Radios chilenas, en una experiencia simple.</Text></View><Text style={styles.version}>1.0</Text></View></View><Text style={styles.note}>Los controles de pantalla de bloqueo y la reproducción en segundo plano se activan en el build Android final. La disponibilidad puede variar según cada stream.</Text></ScreenContainer>;
}
function SettingRow({ icon, title, subtitle, value, onChange }: { icon: any; title: string; subtitle: string; value: boolean; onChange: (v: boolean) => void }) { return <View style={styles.row}><View style={styles.rowIcon}><IconSymbol name={icon} size={20} color="#C8CBE0" /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowSubtitle}>{subtitle}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: "#33394A", true: "#FF6B5F" }} thumbColor="#F5F3EE" /></View> }
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 36 }, back: { width: 38, height: 38, borderRadius: 14, backgroundColor: "#FFFFFF0D", alignItems: "center", justifyContent: "center" }, title: { color: "#F5F3EE", fontSize: 20, fontWeight: "700" }, eyebrow: { color: "#A8B0C2", fontSize: 11, fontWeight: "700", letterSpacing: 1.5, marginBottom: 12 }, group: { borderRadius: 20, backgroundColor: "#FFFFFF08", borderWidth: 1, borderColor: "#FFFFFF10", paddingHorizontal: 16, marginBottom: 30 }, row: { minHeight: 76, flexDirection: "row", alignItems: "center", gap: 13 }, rowIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: "#FFFFFF0D", alignItems: "center", justifyContent: "center" }, rowTitle: { color: "#F5F3EE", fontSize: 15, fontWeight: "600" }, rowSubtitle: { color: "#8D95A7", fontSize: 12, marginTop: 4 }, divider: { height: 1, backgroundColor: "#FFFFFF0C" }, about: { minHeight: 82, flexDirection: "row", alignItems: "center", gap: 13 }, aboutIcon: { width: 44, height: 44, borderRadius: 15, backgroundColor: "#FF6B5F20", alignItems: "center", justifyContent: "center" }, aboutTitle: { color: "#F5F3EE", fontSize: 15, fontWeight: "700" }, aboutText: { color: "#8D95A7", fontSize: 12, marginTop: 5 }, version: { color: "#8D95A7", fontSize: 12 }, note: { color: "#71798C", fontSize: 12, lineHeight: 18, paddingHorizontal: 4 } });
