import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { StationLogo } from "@/components/station-logo";
import { useRadioPlayer } from "@/lib/radio-player";
import { IconSymbol } from "@/components/ui/icon-symbol";
export default function FavoritesScreen() {
  const { favorites, playRadio, toggleFavorite, radios: catalog } = useRadioPlayer();
  const radios = catalog.filter((radio) => favorites.includes(radio.id));
  return <ScreenContainer containerClassName="bg-[#090B12]" className="px-5 pt-3"><View style={styles.header}><View><Text style={styles.eyebrow}>TU COLECCIÓN</Text><Text style={styles.title}>Favoritos</Text></View><Text style={styles.count}>{radios.length}</Text></View><FlatList data={radios} keyExtractor={(r) => r.id} showsVerticalScrollIndicator={false} renderItem={({ item }) => <Pressable onPress={() => playRadio(item)} style={({ pressed }) => [styles.row, pressed && { opacity: 0.75 }]}><StationLogo radio={item} size={54} radius={16} /><View style={{ flex: 1 }}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.frequency}  ·  {item.genre}</Text></View><Pressable onPress={() => toggleFavorite(item.id)} hitSlop={10}><IconSymbol name="heart.fill" size={20} color="#FF6B5F" /></Pressable></Pressable>} ListEmptyComponent={<View style={styles.empty}><View style={styles.emptyIcon}><IconSymbol name="heart" size={28} color="#FF8C7F" /></View><Text style={styles.emptyTitle}>Aún no tienes favoritos</Text><Text style={styles.emptyText}>Guarda tus radios preferidas para encontrarlas aquí.</Text></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 28 }, eyebrow: { color: "#FF8C7F", fontSize: 11, fontWeight: "700", letterSpacing: 1.8, marginBottom: 7 }, title: { color: "#F5F3EE", fontSize: 32, fontWeight: "700", letterSpacing: -1 }, count: { color: "#A8B0C2", fontSize: 14 }, row: { minHeight: 75, borderRadius: 19, backgroundColor: "#FFFFFF08", borderWidth: 1, borderColor: "#FFFFFF0E", padding: 10, marginBottom: 10, flexDirection: "row", alignItems: "center", gap: 13 }, name: { color: "#F5F3EE", fontSize: 15, fontWeight: "600" }, meta: { color: "#8D95A7", fontSize: 12, marginTop: 5 }, empty: { alignItems: "center", paddingTop: 100, paddingHorizontal: 34 }, emptyIcon: { width: 68, height: 68, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: "#FF6B5F18", marginBottom: 18 }, emptyTitle: { color: "#F5F3EE", fontSize: 19, fontWeight: "700", marginBottom: 8 }, emptyText: { color: "#8D95A7", fontSize: 13, lineHeight: 20, textAlign: "center" } });
