import * as WebBrowser from "expo-web-browser";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { StationLogo } from "@/components/station-logo";
import { useRadioPlayer } from "@/lib/radio-player";

export default function RadioDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { radios, currentRadio, isPlaying, isLoading, playRadio, toggleFavorite, isFavorite } = useRadioPlayer();
  const radio = radios.find((item) => item.id === id);

  if (!radio) return <ScreenContainer containerClassName="bg-[#090B12]" className="px-5 pt-3"><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.left" size={22} color="#F5F3EE" /></Pressable><View style={styles.notFound}><Text style={styles.notFoundTitle}>Radio no encontrada</Text><Text style={styles.notFoundText}>La emisora pudo haber cambiado en la última actualización.</Text></View></ScreenContainer>;

  const active = currentRadio?.id === radio.id && isPlaying;
  const openOfficialSite = async () => { if (radio.homepage) await WebBrowser.openBrowserAsync(radio.homepage); };
  return <ScreenContainer containerClassName="bg-[#090B12]" className="px-5 pt-3"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.left" size={22} color="#F5F3EE" /></Pressable><Pressable onPress={() => toggleFavorite(radio.id)} style={styles.back}><IconSymbol name={isFavorite(radio.id) ? "heart.fill" : "heart"} size={20} color={isFavorite(radio.id) ? "#FF6B5F" : "#F5F3EE"} /></Pressable></View><View style={[styles.artwork, { backgroundColor: `${radio.accent}32` }]}><View style={[styles.artGlow, { backgroundColor: `${radio.accent}55` }]} /><StationLogo radio={radio} size={156} radius={42} /></View><Text style={styles.eyebrow}>ESTÁS ESCUCHANDO</Text><Text style={styles.name}>{radio.name}</Text><Text style={styles.meta}>{radio.frequency}  ·  {radio.city}  ·  {radio.genre}</Text><View style={styles.actions}><Pressable onPress={() => playRadio(radio)} style={({ pressed }) => [styles.playButton, pressed && { transform: [{ scale: 0.97 }] }]}><IconSymbol name={active ? "pause.fill" : "play.fill"} size={24} color="#090B12" /><Text style={styles.playText}>{isLoading ? "Conectando" : active ? "Pausar" : "Reproducir"}</Text></Pressable><Pressable onPress={openOfficialSite} disabled={!radio.homepage} style={({ pressed }) => [styles.siteButton, !radio.homepage && styles.disabled, pressed && { opacity: 0.75 }]}><IconSymbol name="globe" size={20} color="#F5F3EE" /><Text style={styles.siteText}>Web oficial</Text></Pressable></View><View style={styles.infoCard}><Text style={styles.infoLabel}>SOBRE LA EMISORA</Text><Text style={styles.description}>{radio.description}</Text>{radio.homepage ? <Text style={styles.url} numberOfLines={1}>{radio.homepage.replace(/^https?:\/\//, "").replace(/\/$/, "")}</Text> : <Text style={styles.unavailable}>Página oficial no disponible</Text>}</View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 35 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 25 }, back: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#FFFFFF0D", borderWidth: 1, borderColor: "#FFFFFF12", alignItems: "center", justifyContent: "center" }, artwork: { height: 270, borderRadius: 34, alignItems: "center", justifyContent: "center", overflow: "hidden", marginBottom: 28, borderWidth: 1, borderColor: "#FFFFFF18" }, artGlow: { position: "absolute", width: 230, height: 230, borderRadius: 130, top: 20, opacity: 0.55 }, eyebrow: { color: "#A8B0C2", fontSize: 11, fontWeight: "700", letterSpacing: 1.5, marginBottom: 10 }, name: { color: "#F5F3EE", fontSize: 31, fontWeight: "700", letterSpacing: -0.8 }, meta: { color: "#A8B0C2", fontSize: 14, marginTop: 8 }, actions: { flexDirection: "row", gap: 10, marginTop: 26, marginBottom: 30 }, playButton: { flex: 1, minHeight: 52, borderRadius: 18, backgroundColor: "#F5F3EE", flexDirection: "row", gap: 10, alignItems: "center", justifyContent: "center" }, playText: { color: "#090B12", fontSize: 14, fontWeight: "700" }, siteButton: { flex: 1, minHeight: 52, borderRadius: 18, backgroundColor: "#FFFFFF0D", borderWidth: 1, borderColor: "#FFFFFF18", flexDirection: "row", gap: 9, alignItems: "center", justifyContent: "center" }, siteText: { color: "#F5F3EE", fontSize: 14, fontWeight: "600" }, disabled: { opacity: 0.45 }, infoCard: { borderRadius: 22, backgroundColor: "#FFFFFF08", borderWidth: 1, borderColor: "#FFFFFF12", padding: 20 }, infoLabel: { color: "#A8B0C2", fontSize: 10, fontWeight: "700", letterSpacing: 1.4, marginBottom: 12 }, description: { color: "#E5E4E1", fontSize: 15, lineHeight: 23 }, url: { color: "#FF8C7F", fontSize: 12, marginTop: 15 }, unavailable: { color: "#777F91", fontSize: 12, marginTop: 15 }, notFound: { paddingTop: 100, alignItems: "center" }, notFoundTitle: { color: "#F5F3EE", fontSize: 20, fontWeight: "700" }, notFoundText: { color: "#8D95A7", fontSize: 13, textAlign: "center", marginTop: 10 } });
